swagger: '2.0'
info:
  description: 'A super cool endpoint for rendering a json list of tracks.'
  version: '1.0.0'
  title: 'YOUR PROJECT NAME'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
schemes:
  - 'http'
paths:
  /healthcheck:
    get:
      summary: 'Check the status of the service'
      description: "If the service is up and running correctly the response will be 'UP'"
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'Service is up and healthy'
          schema:
            $ref: '#/definitions/Health'
        500:
          $ref: '#/responses/500'

responses:
  500:
    description: Internal Server Error

definitions:
  Health:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
          - 'UP'
          - 'DOWN'
